server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/hanan-ayman/configserver
          default-label: main
          clone-on-start: true
          force-pull: true
